---
- hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    img_dir: /opt/rpi_img/
    net: 192.168.1.0
    nfs_ip: 192.168.1.114
    image: 2016-03-18-raspbian-jessie-lite.img
    offset_boot: 4194304
    offset_root: 67108864
  tasks:
    - apt: upgrade=dist update_cache=yes
    - command: mkdir -p /opt/raspberrypi creates=/opt/raspberrypi

    - apt: name=nfs-kernel-server
    - lineinfile: dest=/etc/exports line="/opt/raspberrypi/root {{net}}/24(ro,sync,no_root_squash,no_subtree_check)"

  handlers:

