---
- hosts: 127.0.0.1
  connection: local
  remote_user: chrome-bot
  sudo: yes
  vars:
    img_dir: /opt/rpi_img/
    net: 192.168.1.0
    nfs_ip: 192.168.1.114
    image: 2015-09-24-raspbian-jessie.img
    offset_boot: 4194304
    offset_root: 62914560
  tasks:
    - file: path=/opt/raspberrypi/boot state=directory
    - file: path=/opt/raspberrypi/root state=directory

    - mount: src="{{img_dir}}{{image}}" name="/opt/raspberrypi/boot" fstype="auto" opts="loop,offset={{offset_boot}},noauto" state="mounted"
    - mount: src="{{img_dir}}{{image}}" name="/opt/raspberrypi/root" fstype="auto" opts="loop,offset={{offset_root}},noauto" state="mounted"

    # the pi is unbootable unless it is told not to mount the root filesystem from the card!
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab regexp=".*mmcblk0p2.*" state=absent

    - file: /opt/raspberrypi/boot/cmdline.txt state=absent
    - lineinfile: dest=/opt/raspberrypi/boot/cmdline.txt create=yes line="console=tty1 root=/dev/nfs nfsroot={{nfs_ip}}:/opt/raspberrypi/root ip=192.168.1.201:{{nfs_ip}}:192.168.1.1:255.255.255.0:skia-rpi-NNN:eth0:off:8.8.8.8:8.8.4.4 elevator=deadline fsck.repair=yes rootwait"
    
    # start nfs
    - service: name=nfs-kernel-server state=restarted

    # make sure root stays mounted
    - lineinfile: dest=/etc/cron.d/opt_raspberrypi_root line="* * * * * root /bin/mount /opt/raspberrypi/root" create=yes state=present

    # Remount these at startup
    - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/root" insertbefore="exit 0"
    - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/boot" insertbefore="exit 0"


  handlers:

