---
- hosts: 127.0.0.1
  connection: local
  remote_user: chrome-bot
  sudo: yes
  vars:
    img_dir: /opt/rpi_img/
    net: 192.168.1.0
    nfs_ip: 192.168.1.114
    image: 2016-03-18-raspbian-jessie-lite.img
    # 8192 * 512  
    offset_boot: 4194304
    # 131072 * 512
    offset_root: 67108864
  tasks:
    - file: path=/opt/raspberrypi/boot state=directory
    - file: path=/opt/raspberrypi/root state=directory

    - mount: src="{{img_dir}}{{image}}" name="/opt/raspberrypi/boot" fstype="auto" opts="loop,offset={{offset_boot}},noauto" state="mounted"
    - mount: src="{{img_dir}}{{image}}" name="/opt/raspberrypi/root" fstype="auto" opts="loop,offset={{offset_root}},noauto" state="mounted"

    # Set up mounts
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab regexp=".*mmcblk0p2.*" state=absent
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab line="/dev/mmcblk0p3  /b     ext4    defaults          0       2" state=present
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab line="/dev/mmcblk0p5  /var   ext4    defaults          0       2" state=present
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab line="/dev/mmcblk0p6  /tmp   ext4    defaults          0       2" state=present
    - lineinfile: dest=/opt/raspberrypi/root/etc/fstab line="/dev/mmcblk0p7  /home/chrome-bot   ext4    defaults          0       2" state=present

    - file: path=/opt/raspberrypi/root/b state=directory
    # Make the hostname be set from the cmdline, not etc/hostname
    - file: path=/opt/raspberrypi/root/etc/hostname state=absent
    # Autologin to our user
    - lineinfile: dest=/opt/raspberrypi/root/lib/systemd/system/getty@.service regexp="^ExecStart.*" state=absent
    - lineinfile: dest=/opt/raspberrypi/root/lib/systemd/system/getty@.service line="ExecStart=-/sbin/agetty --autologin chrome-bot --noclear %I $TERM" state=present insertafter="\[Service\]"



    # Set up /boot partition to nfs boot
    - file: path=/opt/raspberrypi/boot/cmdline.txt state=absent
    - lineinfile: dest=/opt/raspberrypi/boot/cmdline.txt create=yes line="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/nfs nfsroot={{nfs_ip}}:/opt/raspberrypi/root ip=192.168.1.201:{{nfs_ip}}:192.168.1.1:255.255.255.0:skia-rpi-NNN:eth0:off:8.8.8.8:8.8.4.4 elevator=deadline fsck.repair=yes rootwait"
    
    # start nfs
    - service: name=nfs-kernel-server state=restarted

    # make sure root stays mounted
    - lineinfile: dest=/etc/cron.d/opt_raspberrypi_root line="* * * * * root /bin/mount /opt/raspberrypi/root" create=yes state=present

    # Remount these at startup
    - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/root" insertbefore="exit 0"
    - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/boot" insertbefore="exit 0"


  handlers:

