---
- hosts: 127.0.0.1
  connection: local
  remote_user: chrome-bot
  sudo: yes
  vars:
    img_dir: /opt/rpi_img/
    net: 192.168.1.0
    nfs_ip: 192.168.1.114
    image: 2015-09-24-raspbian-jessie.img
    offset_boot: 4194304
    offset_root: 62914560
  tasks:

    # Remove configurations that keep our files mounted
    - lineinfile: dest=/etc/cron.d/opt_raspberrypi_root line="* * * * * root /bin/mount /opt/raspberrypi/root" create=no state=absent
    - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/root" state=absent
    - lineinfile: dest=/etc/rc.local line="mount /opt/raspberrypi/boot" state=absent

    - service: name=nfs-kernel-server state=stopped

    - mount: name="/opt/raspberrypi/boot" src="dontcare" fstype="auto" state="unmounted"
    - mount: name="/opt/raspberrypi/root" src="dontcare" fstype="auto" state="unmounted"

  handlers:

